# syntax=docker/dockerfile:1
# Emscripten on top of the Linux native image (gcc/cmake for host bgdc).
#   docker build -t bennugd64-linux -f docker/Dockerfile.linux docker/
#   docker build -t bennugd64-wasm --build-arg EMSCRIPTEN_VERSION=6.0.6 \
#     --build-context bennugd64-linux=docker-image://bennugd64-linux \
#     -f docker/Dockerfile.wasm docker/

FROM bennugd64-linux

ARG EMSCRIPTEN_VERSION=6.0.6
ENV EMSDK=/opt/emsdk \
    PLATFORM=wasm

RUN apt-get update \
    && apt-get install -y --no-install-recommends xz-utils \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://github.com/emscripten-core/emsdk.git /opt/emsdk \
    && /opt/emsdk/emsdk install "${EMSCRIPTEN_VERSION}" \
    && /opt/emsdk/emsdk activate "${EMSCRIPTEN_VERSION}" \
    && chmod -R a+rX /opt/emsdk
