# Cross-compile to Apple tvOS Simulator arm64: host Clang + osxcross ld64.
# Used by docker/Dockerfile.tvos. Do not set CMAKE_SYSTEM_NAME Darwin.

set (CMAKE_SYSTEM_NAME tvOS)
set (CMAKE_SYSTEM_PROCESSOR aarch64)
set (CMAKE_OSX_ARCHITECTURES arm64)
set (CMAKE_OSX_DEPLOYMENT_TARGET "15.0" CACHE STRING "")

set (ENV{TVOS_DEPLOYMENT_TARGET} "${CMAKE_OSX_DEPLOYMENT_TARGET}")

set (CMAKE_C_COMPILER_TARGET arm64-apple-tvos${CMAKE_OSX_DEPLOYMENT_TARGET}-simulator)
set (CMAKE_CXX_COMPILER_TARGET ${CMAKE_C_COMPILER_TARGET})
set (CMAKE_OBJC_COMPILER_TARGET ${CMAKE_C_COMPILER_TARGET})
set (CMAKE_OBJCXX_COMPILER_TARGET ${CMAKE_C_COMPILER_TARGET})
set (CMAKE_ASM_COMPILER_TARGET ${CMAKE_C_COMPILER_TARGET})

if (DEFINED ENV{APPLETVSIMULATOR_SDK} AND EXISTS "$ENV{APPLETVSIMULATOR_SDK}")
  set (CMAKE_OSX_SYSROOT "$ENV{APPLETVSIMULATOR_SDK}" CACHE PATH "")
elseif (EXISTS "/opt/apple/AppleTVSimulator.sdk")
  set (CMAKE_OSX_SYSROOT "/opt/apple/AppleTVSimulator.sdk" CACHE PATH "")
elseif (DEFINED ENV{SDKROOT} AND EXISTS "$ENV{SDKROOT}")
  set (CMAKE_OSX_SYSROOT "$ENV{SDKROOT}" CACHE PATH "")
else ()
  message (FATAL_ERROR
    "AppleTVSimulator.sdk not found (set APPLETVSIMULATOR_SDK or put it in /opt/apple/AppleTVSimulator.sdk)")
endif ()

include (${CMAKE_CURRENT_LIST_DIR}/osxcross-apple-clang.cmake)
include (${CMAKE_CURRENT_LIST_DIR}/osxcross-tools.cmake)

if (CMAKE_LINKER)
  set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fuse-ld=${CMAKE_LINKER}")
  set (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fuse-ld=${CMAKE_LINKER}")
  set (CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -fuse-ld=${CMAKE_LINKER}")
endif ()
