# I/O backend for core/common/files.c: files_$platform.c

function (bennugd_files_native target)
  if (NINTENDO_WII OR PLATFORM_WII)
    target_sources (${target} PRIVATE ${CMAKE_SOURCE_DIR}/core/common/files_wii.c)
  elseif (PLATFORM_PS2 OR PS2)
    target_sources (${target} PRIVATE ${CMAKE_SOURCE_DIR}/core/common/files_ps2.c)
  elseif (PLATFORM_VITA OR VITA)
    target_sources (${target} PRIVATE ${CMAKE_SOURCE_DIR}/core/common/files_vita.c)
  elseif (PLATFORM_PS3 OR PS3)
    target_sources (${target} PRIVATE ${CMAKE_SOURCE_DIR}/core/common/files_ps3.c)
  elseif (PLATFORM_PS4 OR PS4)
    target_sources (${target} PRIVATE ${CMAKE_SOURCE_DIR}/core/common/files_ps4.c)
  elseif (CMAKE_SYSTEM_NAME STREQUAL "iOS")
    target_sources (${target} PRIVATE ${CMAKE_SOURCE_DIR}/core/common/files_ios.c)
  elseif (CMAKE_SYSTEM_NAME STREQUAL "tvOS")
    target_sources (${target} PRIVATE ${CMAKE_SOURCE_DIR}/core/common/files_tvos.c)
  else ()
    target_sources (${target} PRIVATE ${CMAKE_SOURCE_DIR}/core/common/files_native.c)
  endif ()
endfunction ()
