# Cross-compile to Apple iOS arm64: host Clang + osxcross ld64 + iPhoneOS.sdk.
# Used by docker/Dockerfile.ios. Do not set CMAKE_SYSTEM_NAME Darwin.

set (CMAKE_SYSTEM_NAME iOS)
set (CMAKE_SYSTEM_PROCESSOR aarch64)
set (CMAKE_OSX_ARCHITECTURES arm64)
set (CMAKE_OSX_DEPLOYMENT_TARGET "17.0" CACHE STRING "")

set (ENV{IPHONEOS_DEPLOYMENT_TARGET} "${CMAKE_OSX_DEPLOYMENT_TARGET}")

set (CMAKE_C_COMPILER_TARGET arm64-apple-ios${CMAKE_OSX_DEPLOYMENT_TARGET})
set (CMAKE_CXX_COMPILER_TARGET ${CMAKE_C_COMPILER_TARGET})
set (CMAKE_OBJC_COMPILER_TARGET ${CMAKE_C_COMPILER_TARGET})
set (CMAKE_OBJCXX_COMPILER_TARGET ${CMAKE_C_COMPILER_TARGET})
set (CMAKE_ASM_COMPILER_TARGET ${CMAKE_C_COMPILER_TARGET})

if (DEFINED ENV{IPHONEOS_SDK} AND EXISTS "$ENV{IPHONEOS_SDK}")
  set (CMAKE_OSX_SYSROOT "$ENV{IPHONEOS_SDK}" CACHE PATH "")
elseif (EXISTS "/opt/apple/iPhoneOS.sdk")
  set (CMAKE_OSX_SYSROOT "/opt/apple/iPhoneOS.sdk" CACHE PATH "")
elseif (DEFINED ENV{SDKROOT} AND EXISTS "$ENV{SDKROOT}")
  set (CMAKE_OSX_SYSROOT "$ENV{SDKROOT}" CACHE PATH "")
else ()
  message (FATAL_ERROR
    "iPhoneOS.sdk not found (set IPHONEOS_SDK or put it in /opt/apple/iPhoneOS.sdk)")
endif ()

include (${CMAKE_CURRENT_LIST_DIR}/osxcross-apple-clang.cmake)
include (${CMAKE_CURRENT_LIST_DIR}/osxcross-tools.cmake)

if (CMAKE_LINKER)
  set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fuse-ld=${CMAKE_LINKER}")
  set (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fuse-ld=${CMAKE_LINKER}")
  set (CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -fuse-ld=${CMAKE_LINKER}")
endif ()
